AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  emailer_caor

  Sample SAM Template for emailer_caor

Globals:
  Function:
    Timeout: 20

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: EmailFunction
      Handler: edu.uchicago.caor.emailer.App::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Events:
        MailSender:
          Type: Api
          Properties:
            Path: /mail
            Method: POST

Outputs:
  EmailFunction:
    Description: "API Gateway endpoint URL for emailer lambda"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/mail/"
